
name: deploy cloud

on: [workflow_dispatch, push]

jobs:
    deploy-job:
        name: deploy site to cloud server
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: pwd
              run: |
                pwd
                ls
            
            - name: scp files
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PWD }}
                port: 22
                source: docs/*
                target: ${{secrets.HOST_SITE_PATH}}
                strip_components: 1

